### ISSUE TITLE
cannot load puppet/util/pe_conf

### ISSUE THREAD

**Issue by fbour** [tkishel/pe_tune#7]
Hi, 

I'm trying to install pe_tune to check if our settings are fine, and it seems it can't find a dependency : 

[root@pouet ~]# git clone https://github.com/tkishel/pe_tune.git
Cloning into 'pe_tune'...
remote: Counting objects: 635, done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 635 (delta 74), reused 180 (delta 45), pack-reused 419
Receiving objects: 100% (635/635), 125.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (222/222), done.
[root@pouet ~]# rm -f .gitconfig
[root@pouet ~]# chmod +x ./pe_tune/lib/puppet_x/puppetlabs/tune.rb
[root@pouet ~]# ./pe_tune/lib/puppet_x/puppetlabs/tune.rb --current
/opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- puppet/util/pe_conf (LoadError)
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/pe_tune/lib/puppet_x/puppetlabs/tune/configuration.rb:2:in `<top (required)>'
        from ./pe_tune/lib/puppet_x/puppetlabs/tune.rb:823:in `require_relative'
        from ./pe_tune/lib/puppet_x/puppetlabs/tune.rb:823:in `<main>'

I don't think it can't find the pe.conf file, as I checked for permissions and the file is at the correct location I guess ( /etc/puppetlabs/enterprise/conf.d//pe.conf )

Our puppet master's version : 2018.1.4

Any idea what could be missing ? ( a puppet utils ruby library maybe ? )

**Comment by tkishel** [comment]
Hmmm, it is loading`puppet/util/pe_conf.rb` via that require.

```
[root@pe-201814-master ~]# locate puppet/util/pe_conf.rb
/opt/puppetlabs/server/data/environments/enterprise/modules/pe_manager/lib/puppet/util/pe_conf.rb
```

Are you running this on the master?

```
[root@pe-201814-master ~]# ./pe_tune/lib/puppet_x/puppetlabs/tune.rb --current
### Puppet Infrastructure Summary: Found a Monolithic Infrastructure
...
```

Please download it again and retry.

**Comment by fbour** [comment]
I can't find that ruby file : 
`
[root@slv4555p environments]# updatedb
[root@slv4555p environments]# locate puppet/util/pe_conf.rb
[root@slv4555p environments]# locate pe_conf.rb
`
Does it come with the puppet master installation ?

Yes I'm running the script on the master. Note that it's currently in 2018.1.4 but after an upgrade of a 2016.4.13. Maybe something is missing in our puppet master

**Comment by fbour** [comment]
The issue came from our puppet master, don't know why but the directory /opt/puppetlabs/server/data/environments/enterprise  was missing. I reinstalled the pe-modules package and it works fine now

**Comment by tkishel** [comment]
Thanks for the details. Good to hear it is working now.
 I don't know why the pe_manager module would not be installed. 
But for reference:

```
[root@pe-2016413-master ~]# locate puppet/util/pe_conf.rb
/opt/puppetlabs/puppet/cache/lib/puppet/util/pe_conf.rb
/opt/puppetlabs/puppet/modules/pe_manager/lib/puppet/util/pe_conf.rb
/opt/puppetlabs/server/data/enterprise/modules/pe_manager/lib/puppet/util/pe_conf.rb
```

```
[root@pe-2016413-master ~]# /vagrant/pe_tune/lib/puppet_x/puppetlabs/tune.rb --current
### Puppet Infrastructure Summary: Found a Monolithic Infrastructure
...
```
